n1 = input('Digite alguma coisa para fazermos um teste: ')
print('O tipo do formato de {} é de'.format(n1), type(n1))
print('É alfa numérico ? ', n1.isalnum())
print('Só esta em caixa alta ?', n1.isupper())
print('Só tem números ou é numérico ?', n1.isnumeric())
print('É só uma espaço ? ', n1.isspace())
print('É sem caixa alta ? ', n1.islower())
print('Só ta alfabeto ? ', n1.isalpha())
print('Esta em Ascii ? ', n1.isascii())
